### ISSUE TITLE
How to extract all metadata from a oib file and export to a human-readable file (like txt)？

### ISSUE THREAD

**Issue by LibbyLi667** [cgohlke/oiffile#1]
Hi there,

Thanks for bringing such a good python library. I am new to oib image files, and currently wanting to extract the metadata from several oib files using python to either a human-readable file or a python dictionary. Could I do that and how could I get that? Thanks in advance.

**Comment by cgohlke** [comment]
There are many metadata files inside OIB files (oif, txt, pty, roi, lut, bmp), mostly INI style text files, which can be parsed into nested dicts with the `SettingsFile` class.  The main settings file can be accessed via the `OifFile.mainfile` attribute. You can also convert OIB to OIF with the `oib2oif` function. In OIF all files are stored in the file system an can be accessed with a text or image viewer. Please see the [examples](https://github.com/cgohlke/oiffile#examples)

**Comment by LibbyLi667** [comment]
> There are many metadata files inside OIB files (oif, txt, pty, roi, lut, bmp), mostly INI style text files, which can be parsed into nested dicts with the `SettingsFile` class. The main settings file can be accessed via the `OifFile.mainfile` attribute. You can also convert OIB to OIF with the `oib2oif` function. In OIF all files are stored in the file system an can be accessed with a text or image viewer. Please see the [examples](https://github.com/cgohlke/oiffile#examples)

Thanks for the reply. I could extract the metadata now! Just one problem - I saw there are still some information (as listed below, like the Core metadata) that I couldn't see in the oif/mainfile. Any ideas how to get these?
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/xli677/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/xli677/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Key | Value
-- | --
BitsPerPixel | 12
DimensionOrder | XYCZT
IsInterleaved | FALSE
IsRGB | FALSE
LittleEndian | TRUE
PixelType | uint16
Series 0 Name | Series 1
SizeC | 2
SizeT | 1
SizeX | 1024
SizeY | 1024
SizeZ | 1
AS Level | 9999
AbsPositionUnitName | mm
AbsPositionValue | 0
Adjust Outward | 0
Adjust Retrun | 0
AnalogPMTGain | 1
Confocal | ON
CountingPMTGain | 0
CountingPMTOffset | 1.6
CountingPMTVoltage | 0
Image 0 : AnalogPMTOffset | 7
Image 0 : ExcitationOutPutLevel | 5
Image 0 : PMTVoltage | 596
Image 1 : AnalogPMTOffset | 6
Image 1 : ExcitationOutPutLevel | 0.5
Image 1 : PMTVoltage | 657
LightControl | 9999
Location | Y:\MyTardisTestData\good image 02.oib
Magnification | 60
Number | 1
ObjectiveLens NAValue | 1.35
ObjectiveLens Name | UPLSAPO   60X O  NA:1.35
ObjectiveLens WDValue | 9999
Observation Mode | LSM
PMTDetectingMode | Analog
Pan Scale | 2
Path | .\
Piezo AbsPositionUnitName | nm
Piezo AbsPositionValue | 0
PinholeDiameter | 115000
PinholeScale | 1
Resolution | 5
RotationValue | 0
RotationValue After Clip | 0
RotationValue Before Clip | 0
SamplingClock | 250000
ScanSpeed | 4
Step | 0
Time Per Frame | 5360256
Time Per Line | 5183.999
Time Per Pixel | 4
Time Per Series | 32351536
X Pinhole | 5
XPanValue | 299
Y Pinhole | -132
YPanValue | -253
ZoomValue | 3



</body>

</html>

**Comment by cgohlke** [comment]
>  I saw there are still some information (as listed below, like the Core metadata) that I couldn't see in the oif/mainfile

Those look like properties from the OME model. You could check how Bio-Format determines them at <https://github.com/ome/bioformats/blob/v6.6.1/components/formats-gpl/src/loci/formats/in/FV1000Reader.java>.
