### ISSUE TITLE
Inconsistency in axis order 

### ISSUE THREAD

**Issue by Czaki** [cgohlke/oiffile#2]
When updating my code after the breaking change in 2022.2.2 I found that the axis order reported by `OifFIle.axis` (In my case `ZCYX`) is different than returned by `asarray` (In my case `CZYX`)

This behavior is counterintuitive to me.  

The sample file is attached here:
[Image0003_01.zip](https://github.com/cgohlke/oiffile/files/7997067/Image0003_01.zip)

**Comment by cgohlke** [comment]
AFAICT this is not a regression and there are no significant changes. `OifFIle.axes` is read from the mainfile metadata while `asarray` returns the order in which the dimensions are stored in the file sequence.

**Comment by Czaki** [comment]
I see that this is not regression. I earlier use `OifFile.tiffs.axes` which was removed. Now I found that I need to use `OifFile.series[0].axis`. 

But I expect to have a method that will return axis in order of metadata. 

You may treat this issue as a feature request (or maybe a documentation request).
